name: Landing Page Production CD

on:
  release:
    types:
      - released

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn build
      - run: cp conf/robots.txt dist/robots.txt
      - run: cp conf/sitemap.xml dist/sitemap.xml
      - run: cp conf/_redirects dist/_redirects
      - name: Deploy production application to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.PRODUCTION_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=dist --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "PRODUCTION_NETLIFY_SITE_ID"]'
